# Auto-generated by run_test.sh -- DO NOT EDIT -- deleted after run
import torch.testing._internal.common_utils as _cu
_dl = getattr(_cu, 'DEVICE_LIST_SUPPORT_PROFILING_TEST', None)
if _dl is not None and 'privateuse1' not in _dl:
    _cu.DEVICE_LIST_SUPPORT_PROFILING_TEST = list(_dl) + ['privateuse1']
